-- ============================================================
-- DNS 셀프서비스(고객센터.html) 전용 테이블 + 보안(RLS)
-- Supabase 대시보드 → SQL Editor 에 붙여넣고 [Run] 하면 됩니다.
-- 기존 cs_tickets/앱에는 전혀 영향을 주지 않는 독립 테이블입니다.
-- ============================================================

create table if not exists public.self_requests (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  ticket_no   text,
  type        text not null,          -- 영수증용지신청 / 콜백요청
  store_name  text,
  contact     text not null,
  detail      text,
  extra       jsonb,
  status      text not null default '접수'   -- 접수 / 처리중 / 완료
);

alter table public.self_requests enable row level security;

-- 고객(비로그인=anon)은 '신청 등록'만 가능 (조회/수정 불가)
drop policy if exists "anon can insert self_requests" on public.self_requests;
create policy "anon can insert self_requests"
  on public.self_requests for insert to anon with check (true);

-- 직원(로그인=authenticated)은 조회/수정 가능
drop policy if exists "auth can read self_requests" on public.self_requests;
create policy "auth can read self_requests"
  on public.self_requests for select to authenticated using (true);

drop policy if exists "auth can update self_requests" on public.self_requests;
create policy "auth can update self_requests"
  on public.self_requests for update to authenticated using (true) with check (true);

-- 최신순 조회를 위한 인덱스
create index if not exists self_requests_created_idx on public.self_requests (created_at desc);
